### ISSUE TITLE
Package is incomaptible with vite due to https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility

### ISSUE THREAD

**Issue by ZOASR** [scriptex/lastfm-ts-api#30]
Using the package with vite reports an error which points to this specific line in the code: 
https://github.com/scriptex/lastfm-ts-api/blob/62fbe451e28cc2dea04725ac75bc57150e52bcd5/src/api-request.ts#L69
the [vite docs](https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility) say that it's due to of the use of a node module inside of a browser:
> "This is because Vite does not automatically polyfill Node.js modules."
The vite docs recommend patching the package with `pnpm patch`

Probably finding an alternative to these imports is the apparent solution:
https://github.com/scriptex/lastfm-ts-api/blob/62fbe451e28cc2dea04725ac75bc57150e52bcd5/src/api-request.ts#L1-L3

**Comment by scriptex** [comment]
Hey, @ZOASR this package is intented to be used in Node.js environment. 
You might be able to go around these vite errors by using the [vite-plugin-nodes-polyfill](https://www.npmjs.com/package/vite-plugin-node-polyfills) plugin.

**Comment by ZOASR** [comment]
Thanks, i hadn't consider this solution, it works!

**Comment by scriptex** [comment]
Happy to help 😄 closing this one 🚀
